# default config for M3.5 revB
canvas:
  width: 1280
  height: 720

sync:
  demo_fps: 25
  strict_bg_sync: true
  bg_fps: 25
  bg_start_ms: 0

blend:
  feather_px: 5
  alpha_bias: 1.0
  color_match: true
  color_match_strength: 0.5

rule_params:
  scale_base: 1.0
  scale_per_bbox: 0.80
  rot_gain_yaw: 0.9
  rot_gain_roll: 1.0
  transl_gain: 1.0
