name: m3_5_revB_ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: pip install -r requirements.txt
      - name: PyTest
        run: pytest -q
      - name: Demo run
        run: python scripts/demo_colab_like.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: m3_5_demo_out
          path: out/*
